### ISSUE TITLE
no such column team_fundraising_campaign.default_fundraiser_amount

### ISSUE THREAD

**Issue by guzzijones** [dominikszopa/fundraising-website#35]
after a fresh install of master:

I started the server with:
```
python manage.py runserver localhost:8000

```
Error:
```
no such column: team_fundraising_campaign.default_fundraiser_amount
```

**Comment by guzzijones** [comment]
I ended up having to run the migrations and update the database
```
python manage.py makemigrations team_fundraising
python manage.py migrate
```

**Comment by dominikszopa** [comment]
I think your addition of the missing migration in https://github.com/dominikszopa/fundraising-website/pull/36 have fixed this. I checked the steps in the README in a codespace and they seemed to work. Can I close this issue as fixed?

**Comment by guzzijones** [comment]
yes closed. FYI,   I actually have made the site a lot more configurable in my fork.  Let me know if you want a merge request.

**Comment by dominikszopa** [comment]
Yes, I was checking out your commits, you made some great improvements that I missed when I was trying to make it more general. I would like to keep some of the branding in there, but use variables or the db instead. 
Would it be possible for you to do separate merges for the code improvements and the text generalization?
